A=imread('2.jpg');
[M N]=size(A);
R=imnoise2('gaussian',M,N,0.05,0.05);
B=im2double(A);
F=B+R;
g=spfilt(F,'amean');
h=spfilt(F,'gmean');
h1=spfilt(F,'hmean');
c=spfilt(F,'chmean');
max=spfilt(F,'max');
min=spfilt(F,'min');
median=spfilt(F,'median');
mid=spfilt(F,'midpoint');
atrim=spfilt(F,'atrimmed');
subplot(3,4,1);imshow(A,[]);title('Original Image');
subplot(3,4,2);imshow(F,[]);title('Noisy Image');
subplot(3,4,3);imshow(g,[]);title('Arithmetic Mean Filter');
subplot(3,4,4);imshow(h,[]);title('Geometric Mean Filter');
subplot(3,4,5);imshow(h1,[]);title('Harmonic Mean Filter');
subplot(3,4,6);imshow(c,[]);title('Contraharmonic Filter');
subplot(3,4,7);imshow(median,[]);title('Median Filter');
subplot(3,4,8);imshow(max,[]);title('Maximum Filter');
subplot(3,4,9);imshow(min,[]);title('Minimum Filter');
subplot(3,4,10);imshow(mid,[]);title('Mid point Filter');
subplot(3,4,11);imshow(atrim,[]);title('Alpha trimmed Filter');