A=imread('2.jpg');
[M N]=size(A);
R=imnoise2('uniform',M,N,0.04,0.3);
B=im2double(A);
F=B+R;
h=colfilt(F,[3 3],'sliding',@gmean);
f=fspecial('average');
g=imfilter(F,f);
subplot(2,2,1);imshow(A);title('Original Image');
subplot(2,2,2);imshow(F);title('Noisy Image using noise2');
subplot(2,2,3);imshow(g,[]);title('Arithmetic Mean Filter');
subplot(2,2,4);imshow(h,[]);title('Geometric Mean Filter');